Loaded module: cuda/12.3.2
Loaded module: cudnn/v8.9.7.29-prod-cuda-12.X
Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/pytorch-CycleGAN-and-pix2pix/test.py", line 52, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/dtu/p1/johlau/Thesis-Synthex/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/dtu/p1/johlau/Thesis-Synthex/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 192, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/dtu/p1/johlau/Thesis-Synthex/synthex/data/pytorch_model/synthex_512/latest_net_G.pth'
