Loaded module: cuda/11.8
ERROR: Unable to locate a modulefile for 'python3/3.9.18'
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /zhome/4e/b/208805/.local/lib/python3.9/site-packages
sysconfig: /zhome/4e/b/208805/.local/lib64/python3.9/site-packages
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/imageng-drr.py", line 20, in <module>
    patient = deepdrr.Volume.from_nifti(
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/deepdrr/vol/volume.py", line 505, in from_nifti
    hu_values = img.get_fdata()
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/nibabel/dataobj_images.py", line 355, in get_fdata
    data = np.asanyarray(self._dataobj, dtype=dtype)
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 332, in _get_unscaled
    return array_from_file(self._shape,
  File "/zhome/4e/b/208805/.local/lib/python3.9/site-packages/nibabel/volumeutils.py", line 522, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/usr/lib64/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.9/gzip.py", line 495, in read
    uncompress = self._decompressor.decompress(buf, size)
KeyboardInterrupt
