Loaded module: cuda/12.2
/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/keras/src/layers/layer.py:360: UserWarning: `build()` was called on layer 'patch_encoder', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(
0it [00:00, ?it/s]1it [00:03,  3.18s/it]2it [00:04,  2.17s/it]3it [00:05,  1.61s/it]4it [00:06,  1.27s/it]5it [00:07,  1.08s/it]6it [00:08,  1.06s/it]7it [00:08,  1.08it/s]8it [00:09,  1.19it/s]9it [00:10,  1.16it/s]10it [00:11,  1.17it/s]11it [00:11,  1.26it/s]12it [00:12,  1.22it/s]13it [00:12,  1.50it/s]14it [00:13,  1.48it/s]15it [00:14,  1.36it/s]16it [00:15,  1.44it/s]17it [00:15,  1.74it/s]18it [00:16,  1.40it/s]19it [00:17,  1.29it/s]20it [00:18,  1.20it/s]21it [00:19,  1.30it/s]22it [00:19,  1.32it/s]23it [00:20,  1.24it/s]24it [00:21,  1.22it/s]25it [00:22,  1.23it/s]26it [00:23,  1.20it/s]27it [00:23,  1.23it/s]28it [00:24,  1.19it/s]29it [00:25,  1.24it/s]30it [00:26,  1.27it/s]31it [00:27,  1.29it/s]32it [00:27,  1.39it/s]33it [00:28,  1.26it/s]34it [00:29,  1.27it/s]35it [00:30,  1.32it/s]36it [00:30,  1.25it/s]37it [00:31,  1.28it/s]38it [00:32,  1.21it/s]39it [00:33,  1.17it/s]40it [00:34,  1.13it/s]41it [00:35,  1.18it/s]42it [00:36,  1.18it/s]43it [00:37,  1.16it/s]44it [00:37,  1.18it/s]45it [00:39,  1.01s/it]46it [00:40,  1.01it/s]47it [00:40,  1.08it/s]48it [00:41,  1.13it/s]49it [00:42,  1.21it/s]50it [00:43,  1.22it/s]51it [00:44,  1.22it/s]52it [00:44,  1.34it/s]53it [00:45,  1.37it/s]54it [00:46,  1.26it/s]55it [00:47,  1.25it/s]56it [00:47,  1.23it/s]57it [00:48,  1.27it/s]58it [00:49,  1.27it/s]59it [00:50,  1.28it/s]60it [00:50,  1.40it/s]61it [00:51,  1.41it/s]62it [00:52,  1.32it/s]63it [00:53,  1.34it/s]64it [00:53,  1.35it/s]65it [00:54,  1.26it/s]66it [00:55,  1.26it/s]67it [00:56,  1.31it/s]68it [00:57,  1.22it/s]69it [00:58,  1.20it/s]70it [00:58,  1.26it/s]71it [00:59,  1.36it/s]72it [01:00,  1.36it/s]73it [01:01,  1.24it/s]74it [01:01,  1.31it/s]75it [01:02,  1.22it/s]76it [01:03,  1.22it/s]77it [01:04,  1.19it/s]78it [01:05,  1.11it/s]79it [01:06,  1.12it/s]80it [01:06,  1.23it/s]81it [01:07,  1.21it/s]82it [01:08,  1.13it/s]83it [01:09,  1.16it/s]84it [01:10,  1.22it/s]84it [01:10,  1.19it/s]
Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dtu/p1/johlau/Thesis-Synthex/object_detection/crop_regular_image.py", line 53, in <module>
    keras.utils.save_img(file, cropped_image)
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/keras/src/utils/image_utils.py", line 184, in save_img
    img.save(path, format=file_format, **kwargs)
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/PIL/Image.py", line 2459, in save
    save_handler(self, fp, filename)
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 1412, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/dtu/p1/johlau/Thesis-Synthex/.venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 559, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
KeyboardInterrupt
